import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const require=createRequire('/home/talvasconcelos/Work/lnbits_pg/'),{chromium}=require('playwright');
const evidence=fileURLToPath(new URL('../evidence/',import.meta.url));mkdirSync(evidence,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});const page=await context.newPage(),errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});

await page.goto(process.env.BEANSHOW_BASE||'http://127.0.0.1:5021/ext/beanshow/play?test=1',{waitUntil:'networkidle'});
console.log('Parent text', (await page.locator('body').innerText()).slice(0,500));
process.once('uncaughtException',async e=>{console.log('UNCAUGHT',e.message,'ERRORS',errors);const f=page.frames().find(f=>f.url().includes('/ext-frame/'));if(f){console.log('DIAGNOSTIC',await f.evaluate(()=>({phase:window.beanTest?.phase(),count:document.getElementById('countdown')?.textContent,overlay:document.getElementById('overlay-title')?.textContent})));await f.locator('#game').screenshot({path:evidence+'failed-interaction.png'});}await browser.close();process.exit(1);});
const iframe=await page.waitForSelector('iframe.wasm-extension-frame',{timeout:45000}),frame=await iframe.contentFrame();
try{await frame.waitForFunction(()=>window.beanTest&& !document.getElementById('join').disabled,null,{timeout:25000});}catch(e){console.log('INIT ERRORS',errors);console.log('FRAME',await frame.locator('body').innerText());console.log('test status',await frame.evaluate(()=>({test:!!window.beanTest,url:location.href})));await frame.locator('#game').screenshot({path:evidence+'failed-init.png'});await browser.close();throw e;}
await frame.locator('#game').screenshot({path:evidence+'menu.png'});assert.equal(await frame.locator('#difficulty').inputValue(),'easy');
await frame.locator('#name').fill('Screenshot Scout');await frame.getByRole('button',{name:'Purple bean',exact:true}).click();await frame.locator('#join').click();await frame.locator('#lobby').waitFor({state:'visible'});assert.equal(await frame.locator('#roster span').count(),60);await frame.locator('#game').screenshot({path:evidence+'lobby.png'});
await frame.locator('#ready').click();await frame.locator('#overlay').waitFor({state:'visible'});await frame.locator('#continue').click();await frame.waitForFunction(()=>window.beanTest.phase()==='playing',null,{timeout:30000});
await frame.evaluate(()=>{window.beanTest.preview('hitparade');window.beanTest.resume();});await frame.locator('#view').focus();await frame.evaluate(()=>window.beanTest.pose(0,0,0));const screenBefore=await frame.evaluate(()=>window.beanTest.screenX());await page.keyboard.down('d');await page.waitForTimeout(800);await page.keyboard.up('d');assert((await frame.evaluate(()=>window.beanTest.screenX()))>screenBefore,'D must move right on screen');const before=await frame.evaluate(()=>window.beanTest.state().players[0].z);await page.keyboard.down('w');await page.waitForTimeout(1500);await page.keyboard.up('w');const after=await frame.evaluate(()=>window.beanTest.state().players[0].z);assert(after>before+2,'rendered W must move player');
await page.keyboard.press('Space');await page.waitForTimeout(130);assert((await frame.evaluate(()=>window.beanTest.state().players[0].y))>.15,'rendered Space must jump');await page.keyboard.down('w');await page.keyboard.press('Shift');await page.waitForTimeout(150);assert((await frame.evaluate(()=>window.beanTest.state().players[0].diveCooldown))>0,'rendered Shift must dive');await page.keyboard.up('w');await frame.locator('#pause').click();assert.equal(await frame.locator('#overlay-title').innerText(),'Show paused.');await frame.locator('#continue').click();
await frame.locator('#sound').click();assert.equal(await frame.locator('#sound').getAttribute('aria-pressed'),'false');await frame.locator('#sound').click();
const roundIds=await frame.evaluate(()=>window.beanTest.rounds);for(const id of (process.env.SKIP_COURSES?[]:process.env.COURSE_FILTER?roundIds.filter(id=>process.env.COURSE_FILTER.split(',').includes(id)):roundIds)){await frame.evaluate(id=>{window.beanTest.preview(id);window.beanTest.overview();},id);await page.waitForTimeout(180);await frame.locator('#game').screenshot({path:evidence+id+'.png'});console.log('Screenshot',id);}
// A genuinely rendered keyboard crown grab, with a setup pose to avoid replaying the whole course.
await frame.evaluate(()=>{window.beanTest.preview('mountain');window.beanTest.pose(0,90,0);window.beanTest.resume();});await frame.locator('#view').focus();await page.keyboard.down('Space');await page.keyboard.down('e');await frame.waitForFunction(()=>window.beanTest.phase()==='ceremony',null,{timeout:10000});await page.keyboard.up('Space');await page.keyboard.up('e');await frame.locator('#game').screenshot({path:evidence+'ceremony.png'});
await frame.locator('#continue').click();assert.equal(await frame.evaluate(()=>window.beanTest.state().n),10,'Final practice replay resets field');await frame.locator('#overlay-home').click();await frame.locator('#leave').click();await frame.locator('#tour').click();assert.equal(await frame.locator('.course-button').count(),16);await frame.locator('#close-courses').click();
// Complete a five-round show through actual Continue buttons; player controlled by bot simulation here.
await frame.locator('#join').click();await frame.locator('#ready').click();for(let round=0;round<5;round++){await frame.locator('#continue').click();await frame.evaluate(()=>{window.beanTest.stepBot(125);});if(round<4)assert.equal(await frame.evaluate(()=>window.beanTest.phase()),'results');}assert.equal(await frame.evaluate(()=>window.beanTest.phase()),'ceremony');assert.equal(await frame.evaluate(()=>window.beanTest.show().history.length),5);
await context.close();
const mobileContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1});const mobilePage=await mobileContext.newPage();mobilePage.on('pageerror',e=>errors.push(e.message));await mobilePage.goto('http://127.0.0.1:5021/ext/beanshow/play?test=1',{waitUntil:'networkidle'});const mobileFrame=await(await mobilePage.waitForSelector('iframe.wasm-extension-frame')).contentFrame();await mobileFrame.waitForFunction(()=>window.beanTest&&!document.getElementById('join').disabled,null,{timeout:30000});await mobileFrame.locator('#game').screenshot({path:evidence+'mobile-menu.png'});await mobileFrame.locator('#join').click();await mobileFrame.locator('#ready').click();await mobileFrame.locator('#continue').click();await mobileFrame.waitForFunction(()=>window.beanTest.phase()==='playing',null,{timeout:30000});await mobileFrame.evaluate(()=>{window.beanTest.preview('hitparade');window.beanTest.pose(0,0,0);window.beanTest.resume();});
await mobileFrame.locator('#touch').waitFor({state:'visible'});const stick=await mobileFrame.locator('#stick').boundingBox(),zBefore=await mobileFrame.evaluate(()=>window.beanTest.state().players[0].z);await mobilePage.mouse.move(stick.x+stick.width/2,stick.y+stick.height/2);await mobilePage.mouse.down();await mobilePage.mouse.move(stick.x+stick.width/2,stick.y+15);await mobilePage.waitForTimeout(800);await mobilePage.mouse.up();assert((await mobileFrame.evaluate(()=>window.beanTest.state().players[0].z))>zBefore+.5,'mobile joystick moves the bean');
async function tap(control){const r=await mobileFrame.locator(`[data-control="${control}"]`).boundingBox();await mobilePage.touchscreen.tap(r.x+r.width/2,r.y+r.height/2);await mobilePage.waitForTimeout(180);}
await tap('jump');assert((await mobileFrame.evaluate(()=>window.beanTest.state().players[0].y))>.1,'touch jump works');await tap('dive');assert((await mobileFrame.evaluate(()=>window.beanTest.state().players[0].diveCooldown))>0,'touch dive works');await tap('grab');assert((await mobileFrame.evaluate(()=>window.beanTest.state().players[0].grabCooldown))>0,'touch grab works');await mobileFrame.locator('#game').screenshot({path:evidence+'mobile-play.png'});

const report={allCourseImagesPresent:roundIds.every(id=>existsSync(evidence+id+'.png')),keyboardHorizontalDirection:true,practiceReplayResets:true,browser:'Chromium headless / SwiftShader',screenshots:process.env.SKIP_COURSES?0:process.env.COURSE_FILTER?process.env.COURSE_FILTER.split(',').length:roundIds.length,keyboardMovement:true,keyboardJump:true,keyboardDiveButton:true,keyboardCrownGrab:true,pauseResume:true,soundToggle:true,lobbyJoinReady:true,fullShow:'Bot-driven player, rendered Continue buttons',mobile:'390 × 844 touch emulation: joystick, jump, dive and grab passed; no physical device tested',errors};writeFileSync(evidence+'browser-results.json',JSON.stringify(report,null,2)+'\n');assert.deepEqual(errors,[]);await browser.close();console.log('PASS browser controls,',report.screenshots,'screenshots captured this run, full show');
