import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
import {ROUNDS,DT,makeShow,beginRound,step,advanceShow,floorAt,matchPhase} from './sim.js';
import {showManifest} from './component.js';
const report={rounds:[],shows:[],checks:[],notes:['All autonomous runs use botInput for the player too. These are completion checks, not human playtests.']};
assert.equal(JSON.parse(showManifest('{}')).data.rounds.length,16);for(const bad of ['[]','null','0','invalid'])assert.equal(JSON.parse(showManifest(bad)).ok,false);report.checks.push('Manifest accepts only objects; 16 declared rounds.');
function run(s){s.autoPlayer=true;let ticks=0;while(!s.finished&&ticks<Math.ceil((s.def.time+1)/DT)){step(s);ticks++;}assert(s.finished,s.id+' failed to terminate');assert(s.qualified.length>0,s.id+' produced no survivors');assert.equal(new Set(s.qualified).size,s.qualified.length);assert(s.qualified.every(id=>s.players.some(p=>p.id===id)));for(const p of s.players)for(const k of ['x','y','z','vx','vy','vz'])assert(Number.isFinite(p[k]),`${s.id} ${k} non-finite`);if(s.def.kind==='final'){assert.equal(s.qualified.length,1);assert(s.qualified.includes(s.winner));}else assert(s.qualified.length<=s.qualify);return s;}
for(const difficulty of ['easy','normal'])for(const def of ROUNDS.filter(r=>!process.env.ROUND_FILTER||process.env.ROUND_FILTER.split(',').includes(r.id))){let deadlines=0,min=Infinity,max=0,finishes=0,falls=0;for(let seed=1;seed<=8;seed++){const sh=makeShow(seed*1979,difficulty);if(def.kind==='final'){sh.round=4;sh.ids=sh.ids.slice(0,10);}const initial=beginRound(sh,def.id);if(['roll','match'].includes(def.id))assert(initial.players.every(p=>floorAt(initial,p.x,p.z,p.y+.1)),def.id+' unsafe spawn');const s=run(initial);deadlines+=Number(s.timeout);min=Math.min(min,s.time);max=Math.max(max,s.time);finishes+=s.order.length;falls+=s.players.reduce((n,p)=>n+p.falls,0);}report.rounds.push({round:def.id,difficulty,runs:8,deadlines,minSeconds:+min.toFixed(2),maxSeconds:+max.toFixed(2),physicalFinishes:finishes,falls});console.log(def.id,difficulty,deadlines?'deadline '+deadlines:'physical completion');}
for(let seed=1;seed<=12;seed++){const show=makeShow(seed*41,'easy');assert.equal(show.ids.length,60);assert.equal(show.plan.length,5);while(show.phase!=='ceremony'){const s=run(beginRound(show));advanceShow(show,s);}assert.equal(show.history.length,5);assert(Number.isInteger(show.winner));report.shows.push({seed:seed*41,rounds:show.history.map(r=>r.round),winner:show.winner,deadlines:show.history.filter(r=>r.timeout).length});}
const a=run(beginRound(makeShow(5),'doors')),b=run(beginRound(makeShow(5),'doors'));assert.deepEqual(a.qualified,b.qualified);assert.equal(a.time,b.time);report.checks.push('Seeded deterministic replay; 12 complete five-round shows.');
let s=beginRound(makeShow(22),'hitparade'),p=s.players[0];for(let i=0;i<120;i++)step(s,{0:{z:1}});assert(p.z>8);step(s,{0:{jump:true}});assert(p.y>0);const speed=Math.hypot(p.vx,p.vz);step(s,{0:{z:1,dive:true}});assert(Math.hypot(p.vx,p.vz)>speed);for(let i=0;i<120;i++)step(s,{0:{}});assert(Math.hypot(p.vx,p.vz)<.2);report.checks.push('Input-driven acceleration, jumping, diving, friction.');
s=beginRound(makeShow(55),'doors');while(!s.finished)step(s,{0:{}});assert(!s.qualified.includes(0));report.checks.push('An idle human is eliminated; Easy does not award automatic qualification.');
s=beginRound({...makeShow(77),round:4,ids:[0,1,2]},'mountain');p=s.players[0];Object.assign(p,{x:0,z:s.length,y:3,ground:false});step(s,{0:{}});assert(!p.done,'crown must require grab');step(s,{0:{grab:true}});assert.equal(s.winner,0);report.checks.push('Final crown requires grab input.');
// Match phases drive both floor physics and rendering; restoration is between waves.
for(const difficulty of ['easy','normal']){
 const memory=difficulty==='easy'?8:6,choose=difficulty==='easy'?6:4,length=memory+choose+5;
 s=beginRound(makeShow(811,difficulty),'match');const layout=s.tiles.map(t=>t.fruit);assert.equal(new Set(layout).size,2);
 for(const [time,stage] of [[0,'memorise'],[memory,'choose'],[memory+choose,'drop'],[length-2,'reset']]){
  s.time=time;assert.equal(matchPhase(s).stage,stage);
  for(const tile of s.tiles)assert.equal(!!floorAt(s,tile.x,tile.z),stage!=='drop'||tile.fruit===s.matchTarget);
  assert.deepEqual(s.tiles.map(t=>t.fruit),layout,'layout must stay fixed inside a wave');
 }
 for(const [cycle,count] of [[1,4],[2,6]]){s.time=cycle*length-DT;step(s);assert.equal(matchPhase(s).stage,'memorise');assert.equal(new Set(s.tiles.map(t=>t.fruit)).size,count);assert(s.tiles.some(t=>t.fruit===s.matchTarget));}
 s.time=3*length-DT;step(s);assert(s.finished);assert.deepEqual(s.qualified,s.players.filter(p=>p.alive).map(p=>p.id));assert(!s.timeout);
}
s=beginRound({...makeShow(91),ids:[0]},'match');step(s);assert.deepEqual(s.qualified,[0]);const soloShow={...makeShow(91),round:3,ids:[0]};s=run(beginRound(soloShow,'doors'));assert.deepEqual(s.qualified,[0]);
report.checks.push('Match: 2/4/6 fruit waves, exact phase boundaries, fixed layouts, floor consistency, all survivors qualify, singleton progression.');
const listing=JSON.parse(readFileSync('../manifest.json'));assert.deepEqual(listing.repos,[{id:'beanshow',organisation:'lnbits',repository:'beanshow'}]);report.checks.push('Repository discovery manifest points to the requested lnbits/beanshow location.');
const config=JSON.parse(readFileSync('../config.json'));assert.deepEqual(config.permissions,[]);assert.equal(config.api_routes[0].export,'show-manifest');const magic=readFileSync('../wasm/module.wasm').subarray(0,8);assert.equal(magic[4],13,'must be a component, not a core module');report.checks.push('No permissions; config and component export agree.');
writeFileSync(process.env.ROUND_FILTER?'../evidence/spawn-regression.json':'../evidence/bot-results.json',JSON.stringify(report,null,2)+'\n');console.log('PASS',report.rounds.length*8,'individual rounds,',report.shows.length,'full shows');
